name: Build and Test

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    name: Build Electron App
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run quality checks
        run: |
          echo "Running linting and formatting checks..."
          npm run check
          echo "✅ All quality checks passed"

      - name: Package application
        run: |
          echo "Packaging application..."
          npx electron-packager . Typy --platform=win32 --arch=x64 --out=dist --overwrite
          echo "✅ Build completed successfully"

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: typy-windows-build
          path: dist/
          retention-days: 7
